export const dashboardHtml = String.raw`<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Codex Mesh</title>
  <style>
    :root{color-scheme:dark;--bg:#080b10;--panel:#111720;--panel2:#151d28;--line:#263242;--text:#eef4fb;--muted:#91a0b3;--blue:#72adff;--green:#54d58a;--amber:#ffc760;--red:#ff737b;--purple:#bd9cff;--radius:16px}
    *{box-sizing:border-box}html{background:var(--bg)}body{margin:0;min-height:100vh;background:radial-gradient(circle at 10% -10%,#18304c 0,transparent 30%),radial-gradient(circle at 100% 0,#281b43 0,transparent 24%),var(--bg);color:var(--text);font:14px/1.55 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}
    button,input,select{font:inherit;color:inherit}button{min-height:40px;border:1px solid #3b5472;background:#1c3654;padding:8px 13px;border-radius:10px;cursor:pointer;transition:.16s}button:hover{background:#294d74;transform:translateY(-1px)}button.secondary{background:#111821;border-color:var(--line)}
    header{position:sticky;top:0;z-index:4;display:flex;align-items:center;gap:12px;padding:14px clamp(14px,3vw,30px);background:#080b10df;border-bottom:1px solid #233044;backdrop-filter:blur(18px)}h1{font-size:18px;margin:0}.brand{display:flex;align-items:center;gap:10px}.pulse{width:10px;height:10px;border-radius:50%;background:var(--green);box-shadow:0 0 16px var(--green)}.pulse.live{animation:pulse 1.8s infinite}@keyframes pulse{50%{box-shadow:0 0 3px var(--green);opacity:.7}}.sub,.muted{color:var(--muted)}.grow{flex:1}.stats{font-variant-numeric:tabular-nums;color:var(--muted)}
    main{max-width:1480px;margin:auto;padding:22px clamp(12px,3vw,28px);display:grid;grid-template-columns:minmax(280px,350px) minmax(0,1fr);gap:20px}.panel{background:#111720df;border:1px solid var(--line);border-radius:var(--radius);overflow:hidden;box-shadow:0 18px 60px #0004}.panel-title{display:flex;align-items:center;gap:8px;padding:14px 16px;border-bottom:1px solid var(--line)}.panel-title h2{font-size:14px;margin:0}.count{margin-left:auto;color:var(--muted);font-variant-numeric:tabular-nums}.body{padding:14px}
    .node{padding:13px;border:1px solid var(--line);border-radius:12px;margin-bottom:11px;background:linear-gradient(145deg,#151d28,#10161e)}.node-head{display:flex;gap:8px;align-items:center}.online{color:var(--green)}.offline{color:var(--muted)}.labels{color:var(--blue);font-size:12px;margin-top:2px}.thread{padding:7px 0 0 17px;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}details{margin-top:8px}summary{cursor:pointer;color:#cbd7e4}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.toolbar select{min-height:40px;background:#0c1118;border:1px solid var(--line);border-radius:10px;padding:7px 32px 7px 10px}
    .task{margin-bottom:15px;border:1px solid var(--line);border-radius:14px;overflow:hidden;background:#0e141c}.task.running{border-color:#46698e;box-shadow:0 0 0 1px #274867 inset}.task-head{padding:11px 13px;background:#141c26;display:flex;gap:8px;align-items:center;flex-wrap:wrap}.task-route{font-weight:650}.task-time{margin-left:auto;color:var(--muted);font-size:12px}.badge{padding:2px 8px;border-radius:999px;background:#293442;color:var(--amber);font-size:12px}.badge.desktop{background:#173c2a;color:#80e6aa}.badge.background{background:#432c18;color:#ffd18a}.badge.completed{background:#173c2a;color:#80e6aa}.badge.failed{background:#4a2024;color:#ffabb0}.badge.cancelled{background:#332b3d;color:#d7c8e8}.badge.running{background:#173250;color:#90c4ff}.task-summary{padding:11px 13px;color:#ced8e5;border-bottom:1px solid var(--line)}.task-summary summary{color:var(--muted)}.prompt{padding:10px 0 0;white-space:pre-wrap;word-break:break-word;color:#bdc9d8}.result,.error{padding:12px 13px;white-space:pre-wrap;word-break:break-word;border-top:1px solid var(--line)}.result{color:#c8f2d8;background:#102019}.error{color:#ffd0d2;background:#241316}
    .timeline{padding:12px 13px}.timeline-title{display:flex;align-items:center;gap:8px;font-weight:650;margin-bottom:10px}.live-dot{width:7px;height:7px;border-radius:50%;background:var(--blue);animation:pulse 1.4s infinite}.event{position:relative;margin-left:8px;padding:0 0 13px 18px;border-left:1px solid #30445d}.event:last-child{padding-bottom:0}.event:before{content:"";position:absolute;left:-4px;top:5px;width:7px;height:7px;border-radius:50%;background:#5d7898}.event.thinking:before{background:var(--purple)}.event.command:before,.event.tool:before{background:var(--amber)}.event.file:before{background:var(--green)}.event.warning:before{background:var(--red)}.event-head{display:flex;gap:8px;align-items:baseline}.event-title{font-weight:600}.event-time{font-size:11px;color:var(--muted)}.event-detail{margin-top:4px;color:#b9c6d5;white-space:pre-wrap;word-break:break-word;max-height:220px;overflow:auto;background:#0a0f15;padding:8px 9px;border-radius:8px}.thinking .event-detail{color:#d7c8ff;border-left:2px solid #7659a9}.empty{padding:34px;text-align:center;color:var(--muted)}
    #login{position:fixed;inset:0;z-index:10;background:#07090deF;display:grid;place-items:center}.login-card{width:min(430px,90vw);padding:28px;background:var(--panel);border:1px solid var(--line);border-radius:16px}.login-card input{width:100%;margin:14px 0;padding:11px;background:#0b0f15;border:1px solid var(--line);border-radius:10px}.hidden{display:none!important}
    @media(max-width:840px){main{grid-template-columns:1fr;padding:12px}header{padding:11px 12px}.sub,.stats{display:none}.task-time{width:100%;margin-left:0}.panel:first-child{order:2}}
  </style>
</head>
<body>
  <div id="login"><form class="login-card" id="loginForm"><h1>连接 Codex Mesh</h1><p class="sub">输入 Relay 管理 Token。只保存在当前浏览器会话。</p><input id="token" type="password" autocomplete="current-password" placeholder="MESH_MCP_TOKEN" required><button type="submit">进入控制台</button></form></div>
  <header><div class="brand"><span id="relayPulse" class="pulse"></span><h1>Codex Mesh</h1></div><span class="sub">Desktop 协作控制台</span><span class="grow"></span><span id="stats" class="stats"></span><button id="pair">生成配对码</button><button id="logout" class="secondary">退出</button></header>
  <main>
    <section class="panel"><div class="panel-title"><h2>电脑与 Desktop 任务</h2><span id="nodeCount" class="count"></span></div><div id="nodes" class="body"></div></section>
    <section class="panel"><div class="panel-title"><h2>协作任务与实时过程</h2><span id="taskCount" class="count"></span></div><div class="body"><div class="toolbar"><select id="statusFilter"><option value="all">全部状态</option><option value="running">进行中</option><option value="completed">已完成</option><option value="failed">失败</option><option value="cancelled">已停止</option></select><select id="modeFilter"><option value="all">全部执行方式</option><option value="desktop">Desktop 附着</option><option value="background">后台任务</option></select></div><div id="tasks"></div></div></section>
  </main>
  <script>
    const login=document.querySelector('#login'),tokenInput=document.querySelector('#token');let token=sessionStorage.getItem('meshToken')||'',streamAbort=null,refreshTimer=null,snapshot=null;if(token)login.classList.add('hidden');
    const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const statusText={queued:'排队',dispatched:'已派发',running:'进行中',completed:'已完成',failed:'失败',cancelled:'已停止'};
    async function api(path,options={}){const response=await fetch(path,{...options,headers:{'content-type':'application/json','authorization':'Bearer '+token,...options.headers}});if(response.status===401){login.classList.remove('hidden');throw new Error('Token 无效')}if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||response.statusText);return response.json()}
    function eventHtml(e){return '<div class="event '+esc(e.kind)+'"><div class="event-head"><span class="event-title">'+esc(e.title)+'</span><span class="event-time">'+new Date(e.createdAt).toLocaleTimeString()+'</span></div>'+(e.detail?'<div class="event-detail">'+esc(e.detail)+'</div>':'')+'</div>'}
    function render(){if(!snapshot)return;const data=snapshot,online=data.nodes.filter(n=>n.connected).length;document.querySelector('#stats').textContent='Relay '+data.memoryMb+' MB · '+online+'/'+data.nodes.length+' 在线';document.querySelector('#nodeCount').textContent=online+'/'+data.nodes.length;document.querySelector('#taskCount').textContent=data.tasks.length;
      document.querySelector('#nodes').innerHTML=data.nodes.length?data.nodes.map(n=>{const dirs=[...new Set(n.threads.map(t=>t.cwd))].sort(),projectMap=new Map(n.projects.map(p=>[p.path,p]));n.threads.forEach(t=>{if(!projectMap.has(t.cwd))projectMap.set(t.cwd,{path:t.cwd,name:t.cwd.replace(/[\\/]+$/,'').split(/[\\/]/).pop()||t.cwd,threadCount:n.threads.filter(x=>x.cwd===t.cwd).length})});const projects=[...projectMap.values()];return '<div class="node"><div class="node-head"><strong>'+esc(n.id)+'</strong><span class="'+(n.connected?'online':'offline')+'">'+(n.connected?'在线':'离线')+'</span></div><div class="labels">'+esc(n.hostname)+' · '+esc(n.labels.join(', '))+'</div><details open><summary>项目 '+projects.length+'</summary>'+projects.map(p=>'<div class="thread" title="'+esc(p.path)+'">▣ '+esc(p.name)+' · '+p.threadCount+' 任务</div>').join('')+'</details><details><summary>工作目录 '+dirs.length+'</summary>'+dirs.map(d=>'<div class="thread" title="'+esc(d)+'">⌂ '+esc(d)+'</div>').join('')+'</details><details><summary>全部任务 '+n.threads.length+'</summary>'+n.threads.map(t=>'<div class="thread" title="'+esc(t.cwd)+' · '+esc(t.preview)+'">↳ '+esc(t.name||t.preview||t.id)+'</div>').join('')+'</details></div>'}).join(''):'<div class="empty">还没有已配对电脑</div>';
      const sf=document.querySelector('#statusFilter').value,mf=document.querySelector('#modeFilter').value,tasks=data.tasks.filter(t=>(sf==='all'||t.status===sf)&&(mf==='all'||t.executionMode===mf));document.querySelector('#tasks').innerHTML=tasks.length?tasks.map(t=>{const events=t.events||[],live=t.status==='running';return '<article class="task '+esc(t.status)+'"><div class="task-head"><span class="badge '+esc(t.status)+'">'+esc(statusText[t.status]||t.status)+'</span><span class="badge '+esc(t.executionMode||'')+'">'+esc(t.executionMode==='desktop'?'Desktop 附着':t.executionMode==='background'?'后台':'等待连接')+'</span><span class="badge">'+esc(t.metadata?.meshPhase||'直接')+'</span><span class="task-route">'+esc(t.sourceNodeId||'Codex')+' → '+esc(t.targetNodeId)+'</span><span class="task-time">'+new Date(t.createdAt).toLocaleString()+'</span></div><details class="task-summary"><summary>任务指令 · '+esc(t.selectedThreadId||t.threadId||'自动选择')+'</summary><div class="prompt">'+esc(t.prompt)+'</div></details>'+(events.length?'<div class="timeline"><div class="timeline-title">'+(live?'<span class="live-dot"></span>':'')+'实时过程 <span class="muted">'+events.length+' 条</span></div>'+events.map(eventHtml).join('')+'</div>':live?'<div class="timeline muted">等待 Desktop 返回过程事件…</div>':'')+(t.result?'<div class="result">'+esc(t.result)+'</div>':'')+(t.error?'<div class="error">'+esc(t.error)+'</div>':'')+'</article>'}).join(''):'<div class="empty">当前筛选下没有协作任务</div>'}
    async function refresh(){if(!token)return;try{snapshot=await api('/api/snapshot');document.querySelector('#relayPulse').classList.add('live');render()}catch(error){console.error(error);document.querySelector('#relayPulse').classList.remove('live')}}
    function scheduleRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,120)}
    async function startStream(){streamAbort?.abort();if(!token)return;const controller=new AbortController();streamAbort=controller;try{const response=await fetch('/api/events',{headers:{authorization:'Bearer '+token},signal:controller.signal});if(!response.ok)throw new Error('实时连接失败');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const part=await reader.read();if(part.done)break;buffer+=decoder.decode(part.value,{stream:true});let cut;while((cut=buffer.indexOf('\n\n'))>=0){const frame=buffer.slice(0,cut);buffer=buffer.slice(cut+2);if(frame.includes('event: task'))scheduleRefresh()}}}catch(error){if(error.name!=='AbortError'){document.querySelector('#relayPulse').classList.remove('live');setTimeout(startStream,1800)}}}
    document.querySelector('#loginForm').addEventListener('submit',async event=>{event.preventDefault();token=tokenInput.value;try{await api('/api/snapshot');sessionStorage.setItem('meshToken',token);login.classList.add('hidden');await refresh();startStream()}catch(error){alert(error.message)}});document.querySelector('#pair').addEventListener('click',async()=>{try{const p=await api('/api/pairing-code',{method:'POST',body:'{}'});await navigator.clipboard?.writeText(p.code);alert('一次性配对码：'+p.code+'\n10 分钟内有效，已尝试复制。')}catch(error){alert(error.message)}});document.querySelector('#logout').addEventListener('click',()=>{streamAbort?.abort();sessionStorage.removeItem('meshToken');token='';login.classList.remove('hidden')});document.querySelector('#statusFilter').addEventListener('change',render);document.querySelector('#modeFilter').addEventListener('change',render);setInterval(refresh,15000);if(token){refresh();startStream()}
  </script>
</body>
</html>`;
